name: flutter_persistent_value_notifier
description: Allow changes to `ValueNotifier.value` to persist across app restarts.
version: 1.0.0
homepage: https://github.com/lukehutch/flutter_persistent_value_notifier

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  shared_preferences: ^2.1.2
